baseURL = "http://nickodema.github.io"
languageCode = "en-us"
title = "Nikolay Dema"
theme = "ga" # "mainroad" "nofancy" "ananke" "rocktopus"
#theme = "crab"
#theme = "vanilla"
#theme = "academic"
#theme = "mainroad"
#theme = "basics"
#theme = "ananke"
#theme = "rocktopus"
